name: Release Claw Sheath

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build:
    name: Build Verifier Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for softprops/action-gh-release to create releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Build Binaries
        run: |
          chmod +x scripts/build_releases.sh
          ./scripts/build_releases.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
          files: releases/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
